// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWsjK-ND5FvM_Ij1la-iSvxiuJ-c6j9M',
    appId: '1:310190903013:web:2d42232676e75f9ac0ce0c',
    messagingSenderId: '310190903013',
    projectId: 'ai-lecture-assistant-9f11c',
    authDomain: 'ai-lecture-assistant-9f11c.firebaseapp.com',
    storageBucket: 'ai-lecture-assistant-9f11c.firebasestorage.app',
    measurementId: 'G-0TLD5WE53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbsAN65171oLvUwNymcAxkhCLxYuB9MA',
    appId: '1:310190903013:android:a55436784c3bd067c0ce0c',
    messagingSenderId: '310190903013',
    projectId: 'ai-lecture-assistant-9f11c',
    storageBucket: 'ai-lecture-assistant-9f11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-VmPgU4nXQxmfrc3EhQT3b4wiLDujxSg',
    appId: '1:310190903013:ios:16ef821bd8761997c0ce0c',
    messagingSenderId: '310190903013',
    projectId: 'ai-lecture-assistant-9f11c',
    storageBucket: 'ai-lecture-assistant-9f11c.firebasestorage.app',
    iosBundleId: 'com.example.aiLectureAssistant',
  );
}
